version: 2
jobs:
  docker-image-build:
    machine: true
    steps:
      - checkout
      - run:
          name: "Build"
          command: |
            docker build -t caio2k/apisamplejava:${CIRCLE_BRANCH}-${CIRCLE_SHA1} .
      - run:
          name: "Push"
          command: |
            docker tag caio2k/apisamplejava:${CIRCLE_BRANCH}-${CIRCLE_SHA1} caio2k/apisamplejava:${CIRCLE_BRANCH}
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push caio2k/apisamplejava:${CIRCLE_BRANCH}-${CIRCLE_SHA1}
            docker push caio2k/apisamplejava:${CIRCLE_BRANCH}
  docker-image-promote:
    machine: true
    environment:
    steps:
      - run:
          name: "Promote"
          command: |
            docker pull caio2k/apisamplejava:master-${CIRCLE_SHA1}
            docker tag caio2k/apisamplejava:master-${CIRCLE_SHA1} caio2k/apisamplejava:${CIRCLE_TAG}
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push caio2k/apisamplejava:${CIRCLE_TAG}
      - run:
          name: "Clone gitops repository"
          working_directory: ~/workdir
          command: |
            wget https://github.com/github/hub/releases/download/v2.5.1/hub-linux-amd64-2.5.1.tgz
      - deploy:
          name: "Update gitops repository with ${CIRCLE_TAG}"
          working_directory: ~/workdir/apiSampleJava-gitops
          command: |
            git config credential.helper 'cache --timeout=120'
            git config user.email "caio2k@circleci.com"
            git config user.name "GitOps Bot"
            git checkout staging
            git checkout -b release/${CIRCLE_TAG}
            sed -i "s@FROM caio2k/apisamplejava:.*@FROM caio2k/apisamplejava:${CIRCLE_TAG}@g" Dockerfile
            git add Dockerfile
            git commit --allow-empty -m "Update deployment Dockerfile to version ${CIRCLE_TAG}"
            git push -q --set-upstream origin release/${CIRCLE_TAG}
            curl -H "Content-Type: application/json" -X POST -d "{\"title\": \"Released version ${CIRCLE_TAG}\", \"body\": \"Merge new version in staging\", \"head\": \"release/${CIRCLE_TAG}\", \"base\": \"staging\" }" https://api.github.com/repos/caio2k/apiSampleJava-gitops/pulls?access_token=$GITHUB_TOKEN
workflows:
  version: 2
  docker-image:
    jobs:
      - docker-image-build:
          filters:
            tags:
              ignore: /^\d+\.\d+\.\d+$/
      - docker-image-promote:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^\d+\.\d+\.\d+$/
