version: 2
jobs:
  docker-image-build:
    machine: true
    steps:
      - checkout
      - run:
          name: "Build"
          command: |
            docker build -t caio2k/apisamplejava:${CIRCLE_BRANCH}-${CIRCLE_SHA1} .
      - run:
          name: "Push"
          command: |
            docker tag caio2k/apisamplejava:${CIRCLE_BRANCH}-${CIRCLE_SHA1} caio2k/apisamplejava:${CIRCLE_BRANCH}
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push caio2k/apisamplejava:${CIRCLE_BRANCH}-${CIRCLE_SHA1}
            docker push caio2k/apisamplejava:${CIRCLE_BRANCH}
  docker-image-promote:
    machine: true
    environment:
    steps:
      - run:
          name: "Promote"
          command: |
            docker pull caio2k/apisamplejava:master
            docker tag caio2k/apisamplejava:${VERSION} caio2k/apisamplejava:master
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push caio2k/apisamplejava:${VERSION}
      - run:
          name: "Clone gitops repository"
          working_directory: ~/workdir
          command: |
            git clone https://${GITHUB_TOKEN}@github.com/caio2k/apiSampleJava-gitops.git
            git config credential.helper 'cache --timeout=120'
            git config user.email "caio2k@circleci.com"
            git config user.name "GitOps Bot"
      - deploy:
          name: "Update gitops repository with ${VERSION}"
          working_directory: ~/workdir/apiSampleJava-gitops
          command: |
            git checkout staging
            echo "FROM caio2k/apisamplejava:${VERSION}" > Dockerfile
            git commit --allow-empty -m "Update deployment Dockerfile to version ${VERSION}"
            git push -q https://${GITHUB_TOKEN}@github.com/caio2k/apiSampleJava-gitops.git staging

workflows:
  version: 2
  docker-image:
    jobs:
      - docker-image-build:
          filters:
            tags:
              only: /^\d+\.\d+\.\d+$/
      - docker-image-promote:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^\d+\.\d+\.\d+$/
